/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AImage: typeof import('ant-design-vue/es')['Image']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    CaseBannnerA: typeof import('./src/components/CommonBanner/CaseBannnerA.vue')['default']
    CommonBannerA: typeof import('./src/components/CommonBanner/CommonBannerA.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeTopVideoBanner: typeof import('./src/components/HomeTopVideoBanner/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MainLayoutFoot: typeof import('./src/components/Layout/MainLayoutFoot.vue')['default']
    MainLayoutHead: typeof import('./src/components/Layout/MainLayoutHead.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
